<?php
$shipping_method_html = $this->getChildHtml('webpos_shipping_method');
$payment_method_html = $this->getChildHtml('webpos_payment_method');
$review_total_html = $this->getChildHtml('webpos_review');

$result = array('shipping_method' => $shipping_method_html, 
								'payment_method' => $payment_method_html, 
								'review' => $review_total_html);
								
echo Zend_Json::encode($result);
?>