<?php 
	/**
	 * ajaxcart template
	 */
?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	<div class="ajaxcart-product-name" style="margin-left: 18px;">
		<h2 class="product-name">
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(),null,true) ?>">
				<?php echo $this->helper('catalog/output')->productAttribute($_product,$_product->getName(),'name') ?>
			</a>
		</h2>
	</div>
	<div style="margin: 18px;">
		<?php echo $this->getStartFormHtml() ?>
	</div>
	<div class="no-display">
		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
		<input type="hidden" name="related_product" id="related-products-field" value="" />
	</div>
	<?php if ($this->hasOptions()): ?>
		<?php echo $this->getOptionsWrapperHtml() ?>
	<?php endif ?>
	<div style="margin: 15px 24px 15px 24px; float: right;">
		<?php echo $this->getOptionsWrapperBottomHtml() ?>
	</div>
	<?php echo $this->getEndFormHtml() ?>
</form>
<script type="text/javascript">
//<![CDATA[
	var productAddToCartForm = new VarienForm('product_addtocart_form');
	productAddToCartForm.submit = function(button, url) {
		if (this.validator.validate()) {
			var form = this.form;
			var oldUrl = form.action;
			if (url) {
			   form.action = url;
			}
			var e = null;
			try {
				ajaxcart.addToCartHandle(form.action,form.serialize());
			} catch (e) {
			}
			this.form.action = oldUrl;
			if (e) {
				throw e;
			}
			if (button && button != 'undefined') {
				button.disabled = true;
			}
		}
	}.bind(productAddToCartForm);

	productAddToCartForm.submitLight = function(button, url){
		if(this.validator) {
			var nv = Validation.methods;
			delete Validation.methods['required-entry'];
			delete Validation.methods['validate-one-required'];
			delete Validation.methods['validate-one-required-by-name'];
			if (this.validator.validate()) {
				if (url) {
					this.form.action = url;
				}
				ajaxcart.addToCartHandle(this.form.action,this.form.serialize());
			}
			Object.extend(Validation.methods, nv);
		}
	}.bind(productAddToCartForm);
//]]>
</script>